feat: mongodb plugin
nitrictech/membrane pull request #145
Opened 2021-08-26 05:15 UTC by davemooreuws

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1e4fq3a) by [Unito](https://www.unito.io)

2021-08-30 03:39 UTC, tjholm requested changes
one last thing, just a minor formatting error in the mongoOperatorMap, apart from that LGTM

2021-08-30 03:39 UTC, tjholm commented on pkg/plugins/document/mongodb/mongodb.go
> +	">=":   "$gte",
some weird formatting on this line, just some extra spaces from the look of it.

2021-09-01 03:28 UTC, tjholm approved these changes

2021-09-07 02:14 UTC, medgar-nitric approved these changes

2021-09-07 02:20 UTC, merged