Merge contracts
nitrictech/membrane pull request #160
Opened 2021-09-08 22:41 UTC by tjholm

Merges contracts into the membrane, no longer using submodules to manage contracts.

Any outstanding changes to contracts will need to be cherrypicked into this repo following the merge of this change.

Contracts will be published as an archive on each release to simplify contract retrieval into dependent projects (i.e. base sdk auto generation).

2021-09-08 22:46 UTC, medgar-nitric requested changes
I think this should be a good change.

Can you update the README.md to remove the content

```
Contracts Submodule
Initialize the GRPC contracts submodule:

git submodule update --init --recursive
```

2021-09-08 22:47 UTC, medgar-nitric approved these changes

2021-09-08 22:55 UTC, tjholm commented
Note also need to sort out a versioning strategy for this to ensure consistent versioning flow through from the 

> I think this should be a good change.
> 
> Can you update the README.md to remove the content
> 
> ```
> Contracts Submodule
> Initialize the GRPC contracts submodule:
> 
> git submodule update --init --recursive
> ```

Will do :)

2021-09-09 02:30 UTC, medgar-nitric approved these changes

2021-09-09 10:18 UTC, jyecusch approved these changes

2021-09-09 10:18 UTC, merged